# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\project\fluentflash\fluentflash\app\view\SafetyInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SafetyInterface(object):
    def setupUi(self, SafetyInterface):
        SafetyInterface.setObjectName("SafetyInterface")
        SafetyInterface.resize(900, 800)
        self.ScrollArea = ScrollArea(SafetyInterface)
        self.ScrollArea.setGeometry(QtCore.QRect(10, 30, 901, 771))
        self.ScrollArea.setMinimumSize(QtCore.QSize(0, 461))
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 899, 10000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(609, 10000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.SafetyInterfaceTitle = TitleLabel(self.scrollAreaWidgetContents)
        self.SafetyInterfaceTitle.setGeometry(QtCore.QRect(30, 30, 123, 38))
        self.SafetyInterfaceTitle.setObjectName("SafetyInterfaceTitle")
        self.SubtitleLabel = SubtitleLabel(self.scrollAreaWidgetContents)
        self.SubtitleLabel.setGeometry(QtCore.QRect(30, 80, 119, 28))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.AppList = TableWidget(self.scrollAreaWidgetContents)
        self.AppList.setGeometry(QtCore.QRect(30, 120, 561, 441))
        self.AppList.setObjectName("AppList")
        self.AppList.setColumnCount(0)
        self.AppList.setRowCount(0)
        self.ButtonEtractAPKFile = PrimaryPushButton(self.scrollAreaWidgetContents)
        self.ButtonEtractAPKFile.setGeometry(QtCore.QRect(240, 580, 131, 32))
        self.ButtonEtractAPKFile.setObjectName("ButtonEtractAPKFile")
        self.ButtonBackupData = PrimaryPushButton(self.scrollAreaWidgetContents)
        self.ButtonBackupData.setGeometry(QtCore.QRect(460, 580, 131, 32))
        self.ButtonBackupData.setObjectName("ButtonBackupData")
        self.ButtonRefresh = PrimaryPushButton(self.scrollAreaWidgetContents)
        self.ButtonRefresh.setGeometry(QtCore.QRect(20, 580, 131, 32))
        self.ButtonRefresh.setObjectName("ButtonRefresh")
        self.RefreshProgress = IndeterminateProgressBar(self.scrollAreaWidgetContents)
        self.RefreshProgress.setGeometry(QtCore.QRect(20, 570, 570, 4))
        self.RefreshProgress.setObjectName("RefreshProgress")
        self.BackupAExtractProgress = ProgressBar(self.scrollAreaWidgetContents)
        self.BackupAExtractProgress.setGeometry(QtCore.QRect(20, 570, 570, 4))
        self.BackupAExtractProgress.setVal(0.0)
        self.BackupAExtractProgress.setObjectName("BackupAExtractProgress")
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(SafetyInterface)
        QtCore.QMetaObject.connectSlotsByName(SafetyInterface)

    def retranslateUi(self, SafetyInterface):
        _translate = QtCore.QCoreApplication.translate
        SafetyInterface.setWindowTitle(_translate("SafetyInterface", "Form"))
        self.SafetyInterfaceTitle.setText(_translate("SafetyInterface", "Safety"))
        self.SubtitleLabel.setText(_translate("SafetyInterface", "Apps"))
        self.ButtonEtractAPKFile.setText(_translate("SafetyInterface", "Extract APK File"))
        self.ButtonBackupData.setText(_translate("SafetyInterface", "Backup Data"))
        self.ButtonRefresh.setText(_translate("SafetyInterface", "Refresh"))
from qfluentwidgets import IndeterminateProgressBar, PrimaryPushButton, ProgressBar, ScrollArea, SubtitleLabel, TableWidget, TitleLabel
import assets_rc
