# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\coding\myflashbox\app\view\SafetyInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SafetyInterface(object):
    def setupUi(self, SafetyInterface):
        SafetyInterface.setObjectName("SafetyInterface")
        SafetyInterface.resize(900, 800)
        self.ScrollArea = ScrollArea(SafetyInterface)
        self.ScrollArea.setGeometry(QtCore.QRect(10, 30, 901, 801))
        self.ScrollArea.setMinimumSize(QtCore.QSize(0, 461))
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 899, 10000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(609, 10000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.SafetyInterfaceTitle = TitleLabel(self.scrollAreaWidgetContents)
        self.SafetyInterfaceTitle.setGeometry(QtCore.QRect(30, 40, 123, 38))
        self.SafetyInterfaceTitle.setObjectName("SafetyInterfaceTitle")
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(SafetyInterface)
        QtCore.QMetaObject.connectSlotsByName(SafetyInterface)

    def retranslateUi(self, SafetyInterface):
        _translate = QtCore.QCoreApplication.translate
        SafetyInterface.setWindowTitle(_translate("SafetyInterface", "Form"))
        self.SafetyInterfaceTitle.setText(_translate("SafetyInterface", "1234"))
from qfluentwidgets import ScrollArea, TitleLabel
import assets_rc
